CREATE TABLE chatbots (
  id     TEXT PRIMARY KEY,
  name   TEXT NOT NULL,
  prompt TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);